name: Generate ASCII ARTWORK

on: push

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkou Repo
              uses: actions/checkout@v5

            - name: List Repo Files
              run: ls -lrta

            - name: Executing Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh

           #   - name: List files
              #   run: ls

            #   - name: Read file
            #     run: cat README.md